spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: yang0515!!
  security:
    user:
      name: root
      password: root
      roles: ADMIN
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

